import Head from 'next/head'
import Hero from '@/components/Hero'

export default function Home() {
  return (
    <>
      <Head>
        <title>Joe Leahy Creative</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero heading='Joe Leahy' message='Photographer | Engineer'/>
  
    </>
  )
}
